#!/bin/bash
tp="$1"
fd=/home/cjp/fate
projDir=/home/cjp/fateProj
if [ "$tp" = "dev" ]; then
    sudo mount -t overlay overlay -o lowerdir=${projDir}/projStk/1env/fate:${projDir}/projStk/0source/fate,upperdir=${projDir}/projStk/2dev/fate,workdir=${projDir}/tmp $fd
elif [ "$tp" = "env" ]; then
    sudo mount -t overlay overlay -o lowerdir=${projDir}/projStk/0source/fate,upperdir=${projDir}/projStk/1env/fate,workdir=${projDir}/tmp $fd
else
    echo "请输入合法的mount类型如下：env, dev"
fi
echo "mount result:"
mount | grep "overlay on $fd type"