#!/bin/bash
sudo apt install nginx
sudo apt install php-fpm
sudo apt install libxml2-dev libxslt1-dev
sudo apt install libgd-dev
sudo apt-get install libpcre3 libpcre3-dev
sudo apt-get install libssl-dev
sudo apt-get install libmaxminddb-dev libmaxminddb0