#!/bin/bash

# 定义一个函数，用于包装对 bin 目录下脚本的调用
ftc() {
    # 获取脚本名称（第一个参数）
    local script_name="$1"
    # 移除第一个参数，剩下的都是要传递给脚本的参数
    shift
    # 定义 bin 目录的路径
    local bin_path="$(dirname "${BASH_SOURCE[0]}")"
    # 完整脚本路径
    local script_path="${bin_path}/${script_name}"

    # 检查脚本是否存在并且可执行
    if [[ -f "${script_path}" ]]; then
        # 使用 bash 明确调用脚本并传递参数
        bash "${script_path}" "$@"
    else
        # 输出错误消息
        echo "错误：脚本 '${script_name}' 不存在或者不可执行。"
        return 1
    fi
}
echo "命令 'ftc' 已设置，您可以使用 'ftc <cmd> <args>' 来管理FATE框架"

#“层次开发框架”翻译为 "Hierarchical Development Framework"，缩写为 "HDF"。
fthdf() {
  local hdf_scp_dir="$(dirname "${BASH_SOURCE[0]}")"
  if [ "$1" = "cd" ]; then
#    bash $hdf_scp_dir/main "$@"
    cd $(bash $hdf_scp_dir/main "$@")
  else
    bash $hdf_scp_dir/main "$@"
  fi
}
echo "命令 'fthdf' 已设置，您可以使用 'fthdf <cmd> <args>' 来管理FATE存储开发项目，即 'fateProj/projStk/' 的各级目录"
