#!/bin/bash
myPath=`readlink -f $0`
scpPath="$(dirname "$myPath")"
rootPath="$(dirname "$scpPath")"

fd=${rootPath}/fate
bash ${scpPath}/ismount && source ${fd}/bin/clean_env.sh && bash ${fd}/bin/init.sh stop || echo 'FATE 框架未加载，无法停止FATE……'