#!/bin/bash
myPath=`readlink -f $0`
scpPath="$(dirname "$myPath")"
rootPath="$(dirname "$scpPath")"
projDir=${rootPath}/fateProj
stkPath=${projDir}/projStk

source ${scpPath}/__ver__
# 判断ftver变量是否存在
if [ -z "${ftver}" ]; then
  echo "FATE版本未指定"
  exit 1
fi

# 判断/home/cjp/fateProj/projStk/下是否存在与ftver名字相同的子文件夹
if [ ! -d "${stkPath}/0source/${ftver}" ]; then
  echo "FATE版本指定错误，文件夹 '${stkPath}/0source/${ftver}' 不存在……"
  exit 1
fi

echo "FATE版本检查通过，当前挂载的版本：$ftver"

bash ${scpPath}/cleanLogs
if [ $? -eq 0 ]; then
    # 定义源目录
    sourceDir="${rootPath}/fateProj/projStk"

    # 定义目标备份目录
    backupDir="${rootPath}/fateProj/bakup"

    # 创建备份目录，如果它不存在的话
    mkdir -p "${backupDir}"

    # 获取当前时间戳，格式为YYYYmmddHHMMSS
    currentTime=$(date +"%Y%m%d%H%M%S")

    # 定义压缩文件的完整路径
    backupFileName="3dev_${ftver}_${currentTime}.tar.gz"
    backupFilePath="${backupDir}/${backupFileName}"

    # 进行压缩操作
    echo "现在开始备份 '3dev' ……"
    tar -czf "${backupFilePath}" -C "${sourceDir}/3dev" "${ftver}"

    # 输出结果
    echo "备份 '3dev' 完成，备份路径为: ${backupFilePath}"
else
    echo "备份 '3dev' 失败……"
fi




