#!/bin/bash
myPath=`readlink -f $0`
scpPath="$(dirname "$myPath")"
rootPath="$(dirname "$scpPath")"

fd=${rootPath}/fate
source ${fd}/bin/clean_env.sh
${fd}/bin/init.sh stop
sudo umount ${fd}

echo "umount result:"
mount | grep "overlay on $fd type"